version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: forum-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forumuser
      POSTGRES_PASSWORD: forumpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: forum-app
    depends_on:
      - db
    env_file:
      - .docker.env
    ports:
      - "3000:3000"
    command: >
      sh -c "pnpm run db:push && pnpm start"

volumes:
  db_data: